name: pyoti
channels:
  - conda-forge
  - default
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - pyvista
  - gmsh
  - jupyter
  - ipython
  - vtk
  - cython
  - make
  - sympy
  - pip
  - pip:
    - partitionsets
    - gmsh-sdk