name: pyoti
channels:
  - conda-forge
  - anaconda
  - default
dependencies:
  - python=3.11.*
  - numpy
  - scipy
  - cython=3.*
  - make
  - cmake
  - pip
  - ipykernel
  - conda-forge::pyvista
  - conda-forge::gmsh
  - conda-forge::python-gmsh
  - conda-forge::vtk
  - conda-forge::scikit-sparse
  - conda-forge::scikit-umfpack
