name: pyoti
channels:
  - conda-forge
  - anaconda
  - default
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - pyvista
  - imageio-ffmpeg
  - gmsh
  - python-gmsh
  - ipykernel
  - vtk
  - cython
  - make
  - sympy
  - pip
  - ipympl
  - pandas
  - nodejs
  - scikit-umfpack
  - scikit-sparse
  - ipygany
  - ipywidgets
  - panel
  - pip:
    - partitionsets
