name: pyoti
channels:
  - anaconda
  - default
dependencies:
  - python=3.9.*
  - numpy
  - scipy
  - cython=0.29.*
  - make
  - cmake
  - pip
  - ipykernel
  - pyvista
  - gmsh
  - python-gmsh
  - vtk
  - scikit-umfpack
  - scikit-sparse
