name: pyoti
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - pyvista
  - gmsh
  - python-gmsh
  - ipykernel
  - vtk
  - cython
  - make
  - sympy
  - pip
  - ipympl
  - nodejs
  - scikit-umfpack
  - scikit-sparse
  - pip:
    - partitionsets
