package:
  name: pyoti
  version: "1.0.0"

source:
  # git_rev: v1.0.0
  # git_url: https://github.com/imqcam/otilib
  path: ..

build:
  number: 0
  script: |
    mkdir build
    cd build
    cmake ..
    echo "checking SP_DIR"
    echo $SP_DIR
    make
    make gendata
    cp -r pyoti $PREFIX/lib/python$PY_VER/site-packages/pyoti
    cp -r data $PREFIX/lib/python$PY_VER/site-packages/data

requirements:
  build:
    - python=3.9
    - numpy>=1.17
    - scipy
    - pandas
    - cython=0.29
    - make
    - cmake
    - gfortran
    - pip
    - ipykernel
    - conda-forge::pyvista
    - conda-forge::gmsh
    - conda-forge::python-gmsh
    - conda-forge::vtk
    - conda-forge::scikit-sparse>=0.4
    - conda-forge::scikit-umfpack
    - conda-forge::suitesparse=5.10.1
    - conda-forge::mpi=1

  host:
    - python=3.9
    - numpy>=1.17
    - scipy
    - pandas
    - cython=0.29
    - make
    - cmake
    - gfortran
    - pip
    - ipykernel
    - conda-forge::pyvista
    - conda-forge::gmsh
    - conda-forge::python-gmsh
    - conda-forge::vtk
    - conda-forge::scikit-sparse>=0.4
    - conda-forge::scikit-umfpack
    - conda-forge::suitesparse=5.10.1
    - conda-forge::mpi=1

  run:
    - python=3.9
    - numpy>=1.17
    - scipy
    - pandas
    - cython=0.29
    - conda-forge::pyvista
    - conda-forge::gmsh
    - conda-forge::python-gmsh
    - conda-forge::vtk
    - conda-forge::scikit-sparse>=0.4
    - conda-forge::scikit-umfpack
    - conda-forge::suitesparse=5.10.1
    - conda-forge::mpi=1

test:
  imports:
    - pyoti
  commands:
    - python -c "import pyoti"

about:
  home: imqcam/otilib

channels:
  - conda-forge
  - defaults
