name: Build and upload conda package

on:
  # release:
  #   types: [published]
  push:
    branches:
      - conda_package

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]
        arch: [x86_64, arm64]
        exclude:
          - os: ubuntu-latest
            arch: arm64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: pyoti
        auto-update-conda: true
        python-version: 3.9
        channels: conda-forge,defaults
        channel-priority: strict
        architecture: ${{ matrix.arch }}
    - name: Install build tools
      run: |
        conda activate pyoti
        conda install -y conda-build anaconda-client
    - name: Build Conda package
      run: |
        conda activate pyoti
        conda build conda
    - name: Upload Conda package
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        conda activate pyoti
        PACKAGE_PATH=$(conda build conda --output)
        anaconda -t $ANACONDA_TOKEN upload -u eminizer $PACKAGE_PATH --channel main --label main --force
