name: Build and upload conda package

on:
  # release:
  #   types: [published]
  push:
    branches:
      - conda_package

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]
        arch: [x86_64, arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: pyoti
        auto-update-conda: true
        python-version: 3.9
        channels: conda-forge,defaults
        channel-priority: strict
    - name: Set environment variable for sourcing conda (Linux)
      if: runner.os == 'Linux'
      run: |
        echo "RUNNER_OS_SOURCE=/home/runner/.bashrc" >> $GITHUB_ENV
    - name: Set environment variable for sourcing conda (Mac)
      if: runner.os == 'macOS'
      run: |
        echo "RUNNER_OS_SOURCE=/Users/runner/.bash_profile" >> $GITHUB_ENV
    - name: Set architecture environment variable (Mac)
      if: runner.os == 'macOS'
      run: |
        if [[ "${{ matrix.arch }}" == "arm64" ]]; then
          echo "CONDA_SUBDIR=osx-arm64" >> $GITHUB_ENV
          conda config --set subdir osx-arm64
        else
          echo "CONDA_SUBDIR=osx-64" >> $GITHUB_ENV
          conda config --set subdir osx-64
        fi
    - name: Set architecture environment variable (Linux)
      if: runner.os == 'Linux'
      run: |
        echo "CONDA_SUBDIR=linux-64" >> $GITHUB_ENV
        conda config --set subdir linux-64
    - name: Install conda-build and anaconda (Linux/Mac)
      if: runner.os != 'Windows'
      run: |
        conda init bash
        source $RUNNER_OS_SOURCE
        conda activate pyoti
        conda install -y conda-build anaconda-client zstandard
    - name: Install conda-build and anaconda (Windows)
      if: runner.os == 'Windows'
      run: |
        conda init cmd.exe
        conda activate pyoti
        conda install -y conda-build anaconda-client zstandard
    - name: Build Conda package (Linux/Mac)
      if: runner.os != 'Windows'
      run: |
        source $RUNNER_OS_SOURCE
        conda activate pyoti
        conda build conda
    - name: Build Conda package (Windows)
      if: runner.os == 'Windows'
      run: |
        conda activate pyoti
        conda build conda
    - name: Upload Conda package (Linux/Mac)
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      if: runner.os != 'Windows'
      run: |
        source $RUNNER_OS_SOURCE
        conda activate pyoti
        PACKAGE_PATH=$(conda build conda --output)
        anaconda -t $ANACONDA_TOKEN upload -u eminizer $PACKAGE_PATH --channel main --label main --force
    - name: Upload Conda package (Windows)
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      if: runner.os == 'Windows'
      run: |
        conda activate pyoti
        PACKAGE_PATH=$(conda build conda --output)
        anaconda -t $ANACONDA_TOKEN upload -u eminizer $PACKAGE_PATH --channel main --label main --force
